name : 'Hello World Docher Action'
description : 'Say hello to user or a world'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'
outputs:
  time:
    description: 'This time we said hello'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.who-to-greet}}
